# Generated by Django 4.2 on 2023-05-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalagreement',
            name='rentDue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
