# Generated by Django 4.2 on 2023-05-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_rentalagreement_rentdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalagreement',
            name='rentDue',
            field=models.FloatField(default=0.0),
        ),
    ]
