# Generated by Django 4.2 on 2023-05-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_rentalagreement_rentdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalagreement',
            name='rentDate',
            field=models.DateTimeField(),
        ),
    ]
