# Generated by Django 4.2 on 2023-04-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_rentalagreement_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalagreement',
            old_name='accountID',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='rentalagreement',
            old_name='vehicleID',
            new_name='vehicle',
        ),
    ]
