# Generated by Django 4.2 on 2023-04-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_accountid_rentalagreement_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
