# Generated by Django 4.2 on 2023-04-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('accountRole', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleID', models.CharField(max_length=100)),
                ('vehicleName', models.CharField(max_length=100)),
                ('vehicleModel', models.CharField(max_length=100)),
                ('vehicleBrand', models.CharField(max_length=100)),
                ('vehicleManufacturer', models.CharField(max_length=100)),
                ('vehicleType', models.CharField(max_length=100)),
                ('vehicleRentRate', models.FloatField()),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
    ]
