# Generated by Django 4.2 on 2023-04-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_vehicle_id_vehicle_vehicleid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='accountID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
