# Generated by Django 4.2 on 2023-04-13 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_account_id_alter_account_accountid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentID', models.CharField(max_length=100)),
                ('rentDate', models.DateField()),
                ('numberOfDays', models.PositiveIntegerField()),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('vehicleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
            options={
                'db_table': 'rental_agreement',
            },
        ),
    ]
